import type { ExecutionResult } from './types';

export const PT_COMMITTEE_DEMO_DATA: ExecutionResult = {
  success: true,
  duration: 48500,
  summary: 'Compiled comprehensive formulary evidence for Semaglutide from 2,079 sources including FDA approvals, clinical trials, and medical guidelines.',
  details: {
    sourcesQueried: 4,
    dataPointsAnalyzed: 2079,
    recommendationsGenerated: 12,
    aiSummary: {
      executiveSummary: 'Semaglutide demonstrates superior efficacy in glycemic control, weight management, and cardiovascular risk reduction compared to other GLP-1 RAs. With Grade A evidence from multiple international guidelines and proven MACE reduction of 26% in SUSTAIN-6, it represents a first-line therapy option for T2D patients with established CVD. The favorable benefit-risk profile, despite GI-related adverse events, supports formulary inclusion with consideration for tiered placement based on cost considerations.',
      keyHighlights: [
        'Strongest CV benefit in class: 26% MACE reduction (HR 0.74, p<0.001)',
        'Dual benefit: HbA1c reduction of 1.5% AND 4.5 kg weight loss',
        'Grade A recommendation from ADA, AHA, ACC, and AACE',
        'Medicare Part D coverage: 85% of plans, predominantly Tier 2-3',
        'Cost-effective at $13.2K/year vs alternatives ($10.2K-13.5K range)',
      ],
      recentNews: [
        {
          headline: 'FDA Expands Semaglutide Label to Include Cardiovascular Risk Reduction',
          source: 'FDA News Release',
          date: '2024-01-15',
          summary: 'FDA approved updated labeling for semaglutide to reduce risk of CV death, nonfatal MI, and nonfatal stroke in adults with T2D and established CVD.',
        },
        {
          headline: 'ADA 2024 Standards of Care Elevate GLP-1 RAs to First-Line Status',
          source: 'Diabetes Care',
          date: '2024-01-08',
          summary: 'New ADA guidelines recommend GLP-1 receptor agonists like semaglutide as initial therapy for patients with T2D and high CV risk, marking a significant shift in treatment paradigm.',
        },
        {
          headline: 'SELECT Trial Shows Semaglutide Reduces CV Events by 20% in Non-Diabetic Patients',
          source: 'New England Journal of Medicine',
          date: '2023-11-11',
          summary: 'Landmark SELECT trial demonstrates cardiovascular benefits of semaglutide extend beyond diabetes, with 20% reduction in major adverse CV events in obese patients without diabetes.',
        },
      ],
    },
    drugProfile: {
      name: 'Semaglutide (Ozempic/Wegovy)',
      genericName: 'Semaglutide',
      brandNames: ['Ozempic', 'Wegovy', 'Rybelsus'],
      manufacturer: 'Novo Nordisk',
      fdaApprovalDate: 'December 2017',
      drugClass: 'GLP-1 Receptor Agonist',
      dosingSchedule: 'Weekly',
      indications: ['Type 2 Diabetes', 'Weight Management', 'Cardiovascular Risk Reduction'],
      efficacyRate: 68.8,
      adverseEvents: 12.4,
      costPerYear: 13200,
      hba1cReduction: 1.5,
      hba1cRange: '-1.2% to -1.8%',
      weightLoss: 4.5,
      weightLossRange: '-3.5 to -6.5 kg',
      cvBenefit: '↓ 26% MACE',
      maceReduction: 26,
    },
    clinicalTrials: [
      {
        id: 'NCT01720446',
        name: 'SUSTAIN-6',
        phase: 'Phase 3',
        trialType: 'Cardiovascular Outcomes Trial (CVOT)',
        participants: 3297,
        population: 'Patients with T2D at high CV risk',
        duration: '104 weeks',
        primaryOutcome: 'CV death, nonfatal MI, or nonfatal stroke (MACE)',
        comparator: 'Placebo',
        result: '26% reduction in primary endpoint (HR 0.74, 95% CI: 0.58-0.95, p<0.001)',
        maceResults: {
          treatment: 6.6,
          control: 8.9,
          hazardRatio: 0.74,
          confidenceInterval: '0.58-0.95',
          pValue: '<0.001',
        },
        hba1cResults: {
          treatment: -1.1,
          control: -0.4,
        },
        weightResults: {
          treatment: -3.6,
          control: -0.7,
        },
        publicationDate: '2016-09-15',
        nctId: 'NCT01720446',
        publicationLink: 'https://pubmed.ncbi.nlm.nih.gov/27633186/',
      },
      {
        id: 'NCT03548935',
        name: 'STEP-1',
        phase: 'Phase 3',
        trialType: 'Weight Management Trial',
        participants: 1961,
        population: 'Adults with obesity without diabetes',
        duration: '68 weeks',
        primaryOutcome: 'Weight loss ≥5% from baseline',
        comparator: 'Placebo',
        result: '86.4% achieved ≥5% weight loss vs 31.5% placebo (p<0.001)',
        hba1cResults: {
          treatment: -0.45,
          control: -0.15,
        },
        weightResults: {
          treatment: -14.9,
          control: -2.4,
        },
        publicationDate: '2021-02-10',
        nctId: 'NCT03548935',
        publicationLink: 'https://pubmed.ncbi.nlm.nih.gov/33567185/',
      },
      {
        id: 'NCT02692716',
        name: 'PIONEER-6',
        phase: 'Phase 3',
        trialType: 'CV Safety Trial',
        participants: 3183,
        population: 'Patients with T2D at high CV risk',
        duration: '15.9 months',
        primaryOutcome: 'CV safety (MACE non-inferiority)',
        comparator: 'Placebo',
        result: 'Non-inferior for MACE (HR 0.79, 95% CI: 0.57-1.11)',
        maceResults: {
          treatment: 3.8,
          control: 4.8,
          hazardRatio: 0.79,
          confidenceInterval: '0.57-1.11',
          pValue: '0.17',
        },
        hba1cResults: {
          treatment: -1.0,
          control: -0.3,
        },
        weightResults: {
          treatment: -3.8,
          control: -0.9,
        },
        publicationDate: '2019-06-11',
        nctId: 'NCT02692716',
        publicationLink: 'https://pubmed.ncbi.nlm.nih.gov/31185157/',
      },
    ],
    guidelines: [
      {
        organization: 'American Diabetes Association (ADA)',
        recommendation: 'Recommended as first-line therapy for T2D with established CVD or indicators of high CV risk',
        evidenceLevel: 'Grade A',
        yearPublished: 2024,
      },
      {
        organization: 'American Heart Association (AHA)',
        recommendation: 'GLP-1 RAs like semaglutide reduce CV events in T2D patients and should be prioritized in patients with ASCVD',
        evidenceLevel: 'Class I, Level A',
        yearPublished: 2024,
      },
      {
        organization: 'American College of Cardiology (ACC)',
        recommendation: 'Preferred agent for diabetes patients with atherosclerotic CVD due to proven CV benefit',
        evidenceLevel: 'Strong Recommendation',
        yearPublished: 2023,
      },
      {
        organization: 'American Association of Clinical Endocrinology (AACE)',
        recommendation: 'GLP-1 RAs with CV benefit (including semaglutide) recommended for most patients with T2D',
        evidenceLevel: 'Grade A',
        yearPublished: 2024,
      },
    ],
    safetyData: {
      blackBoxWarnings: [
        'Risk of thyroid C-cell tumors based on rodent studies. Contraindicated in patients with personal or family history of medullary thyroid carcinoma (MTC) or in patients with Multiple Endocrine Neoplasia syndrome type 2 (MEN 2).',
      ],
      adverseEvents: [
        { event: 'Nausea', treatmentRate: 20.3, controlRate: 5.6 },
        { event: 'Diarrhea', treatmentRate: 8.9, controlRate: 3.1 },
        { event: 'Vomiting', treatmentRate: 9.2, controlRate: 2.3 },
        { event: 'Constipation', treatmentRate: 5.4, controlRate: 2.8 },
        { event: 'Abdominal pain', treatmentRate: 5.7, controlRate: 2.9 },
        { event: 'Decreased appetite', treatmentRate: 9.8, controlRate: 1.2 },
      ],
      seriousAdverseEvents: [
        { event: 'Acute pancreatitis', incidence: 0.3, notes: 'Rare, similar to other GLP-1s' },
        { event: 'Diabetic retinopathy complications', incidence: 3.0, notes: 'Higher in SUSTAIN-6, particularly with rapid glucose lowering' },
        { event: 'Acute kidney injury', incidence: 0.4, notes: 'Usually related to dehydration from GI effects' },
      ],
      warnings: [
        'Pancreatitis risk - discontinue if suspected',
        'Diabetic retinopathy complications in patients with history of retinopathy',
        'Acute kidney injury - monitor renal function in at-risk patients',
        'Hypersensitivity reactions including anaphylaxis and angioedema',
        'Hypoglycemia when used with insulin or insulin secretagogues',
        'Acute gallbladder disease',
      ],
      discontinuationRate: 4.5,
    },
    evidenceQuality: {
      totalTrials: 10,
      trialSeries: 'SUSTAIN 1-10, PIONEER 1-8, STEP 1-5',
      totalPatients: 8400,
      durationRange: '12-104 weeks',
      rctCount: 10,
      doubleBlindCount: 10,
      activeControlCount: 6,
      hasCVOT: true,
      population: {
        meanAge: 57.2,
        ageRange: '18-85 years',
        femalePercent: 48.3,
        baselineHbA1c: 8.1,
        diabetesDuration: 8.5,
        racialBreakdown: {
          white: 72,
          black: 8,
          asian: 15,
        },
      },
    },
    formularyStatus: {
      medicareCoverage: {
        coveragePercent: 85,
        tierDistribution: {
          tier1: 5,
          tier2: 28,
          tier3: 52,
          tier4: 10,
          tier5: 5,
        },
      },
      pbmStatus: [
        { pbm: 'CVS Caremark', status: 'Covered', tier: 3, notes: 'Prior authorization required for dosages >1mg' },
        { pbm: 'Express Scripts', status: 'Covered', tier: 3, notes: 'Step therapy preferred' },
        { pbm: 'OptumRx', status: 'Covered', tier: 2, notes: 'Preferred GLP-1 RA' },
      ],
      vaFormulary: {
        status: 'Formulary',
        criteria: 'No restrictions',
      },
    },
    comparatorDrugs: [
      { name: 'Tirzepatide (Mounjaro)', efficacy: 72.4, cost: 13500, hba1c: -2.1, weightLoss: -12.4, maceReduction: undefined },
      { name: 'Dulaglutide (Trulicity)', efficacy: 61.2, cost: 11800, hba1c: -1.2, weightLoss: -2.9, maceReduction: 12 },
      { name: 'Liraglutide (Victoza)', efficacy: 58.9, cost: 10200, hba1c: -1.1, weightLoss: -2.3, maceReduction: 13 },
    ],
    updates: [
      { type: 'indication', message: 'FDA approved for cardiovascular risk reduction in adults with T2D', date: '2020-01-24' },
      { type: 'guideline', message: 'ADA Standards of Care updated to include GLP-1 RAs as first-line for high CV risk', date: '2024-01-15' },
    ],
  },
  logs: [],
};

export const PRIOR_AUTH_DEMO_DATA: ExecutionResult = {
  success: true,
  duration: 51200,
  summary: 'Generated comprehensive prior authorization intelligence for Dupixent including 4 pivotal clinical trials, 5 international guidelines, 9 PA criteria, and payer policy comparisons across 12+ health plans.',
  details: {
    sourcesQueried: 6,
    dataPointsAnalyzed: 2444,
    recommendationsGenerated: 15,
    aiSummary: {
      executiveSummary: 'Dupixent (dupilumab) has established itself as the first-line biologic for moderate-to-severe atopic dermatitis with robust clinical evidence from SOLO and CHRONOS trials. The favorable safety profile (lower discontinuation rate of 1.9% vs systemic immunosuppressants) and strong guideline support from AAD and AAAAI justify prior authorization approval when topical therapies prove inadequate. Payer policies consistently require documented failure of topical corticosteroids and disease severity scoring (EASI ≥16), with 78% Medicare Part D coverage predominantly in Tier 4-5.',
      keyHighlights: [
        'First-line biologic status: AAD/AAAAI Grade A recommendation',
        'Superior efficacy: 38% IGA clearance vs 10% placebo (SOLO 1)',
        'Excellent safety: 1.9% discontinuation rate, lower than systemic immunosuppressants',
        'Consistent PA criteria: 95% of payers require topical failure + EASI/IGA documentation',
        'Five FDA-approved indications expanding coverage justification',
      ],
      recentNews: [
        {
          headline: 'FDA Approves Dupixent for Prurigo Nodularis, Fifth Indication',
          source: 'FDA News Release',
          date: '2022-09-19',
          summary: 'FDA granted approval for dupilumab to treat prurigo nodularis in adults, expanding the drug\'s approved indications and strengthening prior authorization justification for dermatologic conditions.',
        },
        {
          headline: 'CMS Updates Coverage Policy: Dupixent Now Requires EASI Documentation',
          source: 'CMS Policy Update',
          date: '2023-06-15',
          summary: 'CMS National Coverage Determination now mandates validated disease severity scoring (EASI or IGA) for dupilumab prior authorization, standardizing approval criteria across Medicare Advantage plans.',
        },
        {
          headline: 'AAD Guidelines: Dupixent Recommended as First-Line Systemic for Moderate-Severe AD',
          source: 'Journal of the American Academy of Dermatology',
          date: '2024-02-01',
          summary: 'Updated AAD clinical guidelines elevate dupilumab to preferred first-line systemic therapy for adults with moderate-to-severe atopic dermatitis based on superior efficacy and safety data.',
        },
      ],
    },
    drugProfile: {
      name: 'Dupixent (Dupilumab)',
      genericName: 'Dupilumab',
      brandNames: ['Dupixent'],
      manufacturer: 'Sanofi/Regeneron',
      fdaApprovalDate: 'March 2017',
      drugClass: 'IL-4/IL-13 Inhibitor',
      dosingSchedule: 'Every 2 weeks',
      indications: [
        'Atopic Dermatitis (moderate-to-severe)',
        'Asthma (moderate-to-severe eosinophilic/oral corticosteroid-dependent)',
        'Chronic Rhinosinusitis with Nasal Polyps',
        'Eosinophilic Esophagitis',
        'Prurigo Nodularis',
      ],
      efficacyRate: 69.1,
      adverseEvents: 8.7,
      costPerYear: 39000,
      // PA-specific metrics for atopic dermatitis
      easiImprovement: 75, // EASI-75 response rate
      igaClearance: 38, // IGA 0/1 clearance rate
    },
    clinicalTrials: [
      {
        id: 'NCT02277743',
        name: 'SOLO 1',
        phase: 'Phase 3',
        trialType: 'Efficacy and Safety Trial',
        participants: 671,
        population: 'Adults with moderate-to-severe AD inadequately controlled with topical therapies',
        duration: '16 weeks',
        primaryOutcome: 'IGA score 0 or 1 and ≥75% improvement in EASI score (EASI-75)',
        comparator: 'Placebo',
        result: '38% achieved IGA 0/1 vs 10% placebo; 51% achieved EASI-75 vs 15% placebo (p<0.0001)',
        publicationDate: '2016-12-15',
        nctId: 'NCT02277743',
        publicationLink: 'https://pubmed.ncbi.nlm.nih.gov/27690741/',
      },
      {
        id: 'NCT02277769',
        name: 'SOLO 2',
        phase: 'Phase 3',
        trialType: 'Efficacy and Safety Trial',
        participants: 708,
        population: 'Adults with moderate-to-severe AD inadequately controlled with topical therapies',
        duration: '16 weeks',
        primaryOutcome: 'IGA score 0 or 1 and ≥75% improvement in EASI score (EASI-75)',
        comparator: 'Placebo',
        result: '36% achieved IGA 0/1 vs 9% placebo; 44% achieved EASI-75 vs 12% placebo (p<0.0001)',
        publicationDate: '2016-12-15',
        nctId: 'NCT02277769',
        publicationLink: 'https://pubmed.ncbi.nlm.nih.gov/27690741/',
      },
      {
        id: 'NCT02260986',
        name: 'CHRONOS',
        phase: 'Phase 3',
        trialType: 'Long-term Safety and Efficacy Trial',
        participants: 740,
        population: 'Adults with moderate-to-severe AD',
        duration: '52 weeks',
        primaryOutcome: 'Long-term EASI-75 response and safety profile',
        comparator: 'Placebo + topical corticosteroids',
        result: '65% maintained EASI-75 at week 52 with dupilumab vs 23% placebo (p<0.0001)',
        publicationDate: '2017-01-05',
        nctId: 'NCT02260986',
        publicationLink: 'https://pubmed.ncbi.nlm.nih.gov/28052915/',
      },
      {
        id: 'NCT03054428',
        name: 'LIBERTY AD CAFÉ',
        phase: 'Phase 3',
        trialType: 'Head-to-Head Comparator Trial',
        participants: 325,
        population: 'Adults with moderate-to-severe AD inadequately controlled or intolerant to cyclosporine',
        duration: '16 weeks',
        primaryOutcome: 'EASI-75 response rate',
        comparator: 'Cyclosporine or placebo',
        result: '59% achieved EASI-75 vs 30% placebo in cyclosporine-experienced patients (p<0.001)',
        publicationDate: '2019-04-02',
        nctId: 'NCT03054428',
        publicationLink: 'https://pubmed.ncbi.nlm.nih.gov/30738953/',
      },
    ],
    paCriteria: [
      {
        criteriaType: 'Diagnosis Documentation',
        description: 'Documented diagnosis of moderate-to-severe atopic dermatitis by board-certified dermatologist, allergist, or immunologist with supporting clinical notes',
        required: true,
      },
      {
        criteriaType: 'Disease Severity Assessment',
        description: 'EASI score ≥16, OR IGA score ≥3, OR BSA involvement ≥10% documented within past 30 days',
        required: true,
      },
      {
        criteriaType: 'Topical Therapy Trial',
        description: 'Inadequate response to medium-to-high potency topical corticosteroids for ≥4 consecutive weeks, OR documented contraindication/intolerance',
        required: true,
      },
      {
        criteriaType: 'Systemic Immunosuppressant Trial',
        description: 'Trial of ≥1 systemic immunosuppressant (methotrexate, cyclosporine, azathioprine, or mycophenolate) for ≥3 months with inadequate response, OR documented contraindication',
        required: true,
      },
      {
        criteriaType: 'Age and FDA Indication',
        description: 'Patient age ≥6 months for atopic dermatitis indication (age requirements vary by indication)',
        required: true,
      },
      {
        criteriaType: 'Prescriber Qualifications',
        description: 'Prescribed by or in consultation with board-certified dermatologist, allergist, or immunologist with documentation of specialist evaluation',
        required: false,
      },
      {
        criteriaType: 'Prior Biologic Therapy',
        description: 'If switching from another biologic, documentation of inadequate response or intolerance required',
        required: false,
      },
      {
        criteriaType: 'Quantity Limits',
        description: 'Maximum 2 syringes per 28 days (standard dosing); higher quantities require additional documentation',
        required: false,
      },
      {
        criteriaType: 'Reauthorization Requirements',
        description: 'Annual reauthorization required with documented EASI/IGA improvement of ≥50% from baseline or clinical justification for continuation',
        required: false,
      },
    ],
    guidelines: [
      {
        organization: 'American Academy of Dermatology (AAD)',
        recommendation: 'Dupilumab is recommended for moderate-to-severe atopic dermatitis inadequately controlled with topical prescription therapies or when those therapies are not advisable. Should be considered as first-line systemic therapy.',
        evidenceLevel: 'Strong Recommendation, Level A',
        yearPublished: 2024,
      },
      {
        organization: 'CMS National Coverage Determination',
        recommendation: 'Covered when prior treatments have failed and disease severity is documented with validated scoring systems (EASI, IGA, or BSA). Requires specialist evaluation and documentation of systemic therapy trial.',
        evidenceLevel: 'Policy Guideline',
        yearPublished: 2023,
      },
      {
        organization: 'American Academy of Allergy, Asthma & Immunology (AAAAI)',
        recommendation: 'First-line biologic for moderate-to-severe AD with strong efficacy and favorable safety profile. Superior to conventional immunosuppressants in long-term management.',
        evidenceLevel: 'Grade A Evidence',
        yearPublished: 2023,
      },
      {
        organization: 'European Academy of Dermatology and Venereology (EADV)',
        recommendation: 'Strongly recommended as first-line systemic treatment for adults with moderate-to-severe AD. Can be used in combination with topical therapy.',
        evidenceLevel: 'Strong Recommendation',
        yearPublished: 2024,
      },
      {
        organization: 'National Institute for Health and Care Excellence (NICE)',
        recommendation: 'Recommended as option for treating moderate-to-severe AD in adults if disease has not responded to systemic immunosuppressants or these are contraindicated or not tolerated',
        evidenceLevel: 'Technology Appraisal TA534',
        yearPublished: 2023,
      },
    ],
    safetyData: {
      adverseEvents: [
        { event: 'Injection site reactions', treatmentRate: 10.1, controlRate: 8.2 },
        { event: 'Conjunctivitis', treatmentRate: 9.9, controlRate: 2.9 },
        { event: 'Blepharitis', treatmentRate: 2.1, controlRate: 0.4 },
        { event: 'Oral herpes', treatmentRate: 3.4, controlRate: 2.1 },
        { event: 'Keratitis', treatmentRate: 0.7, controlRate: 0.1 },
      ],
      seriousAdverseEvents: [
        { event: 'Serious infections', incidence: 0.8, notes: 'Similar to placebo' },
        { event: 'Eosinophilia', incidence: 0.5, notes: 'Transient, usually asymptomatic' },
      ],
      warnings: [
        'Hypersensitivity reactions - discontinue if severe reaction occurs',
        'Conjunctivitis and keratitis - monitor eye symptoms',
        'Eosinophilic conditions - monitor for vasculitic rash, worsening pulmonary symptoms',
        'Parasitic (helminth) infections - treat before initiating therapy',
        'Do not use for acute bronchospasm or status asthmaticus',
      ],
      discontinuationRate: 1.9,
    },
    evidenceQuality: {
      totalTrials: 8,
      trialSeries: 'SOLO 1-2, CHRONOS, CAFÉ, LIBERTY AD studies',
      totalPatients: 3200,
      durationRange: '16-52 weeks',
      rctCount: 8,
      doubleBlindCount: 8,
      activeControlCount: 2,
      hasCVOT: false,
      population: {
        meanAge: 38.4,
        ageRange: '6 months-75 years',
        femalePercent: 42.1,
        racialBreakdown: {
          white: 68,
          black: 12,
          asian: 15,
        },
      },
    },
    formularyStatus: {
      medicareCoverage: {
        coveragePercent: 78,
        tierDistribution: {
          tier1: 0,
          tier2: 0,
          tier3: 15,
          tier4: 48,
          tier5: 37,
        },
      },
      pbmStatus: [
        { pbm: 'CVS Caremark', status: 'Covered', tier: 4, notes: 'Prior authorization required, step therapy through systemic immunosuppressants' },
        { pbm: 'Express Scripts', status: 'Covered', tier: 4, notes: 'Requires documented trial of methotrexate or cyclosporine' },
        { pbm: 'OptumRx', status: 'Covered', tier: 5, notes: 'Specialty medication, PA required' },
      ],
      vaFormulary: {
        status: 'Non-Formulary',
        criteria: 'Requires VISN approval for severe refractory cases',
      },
    },
    comparatorDrugs: [
      { name: 'Rinvoq (Upadacitinib)', efficacy: 71.3, cost: 42000 },
      { name: 'Cibinqo (Abrocitinib)', efficacy: 65.8, cost: 38500 },
      { name: 'Adbry (Tralokinumab)', efficacy: 62.4, cost: 41000 },
    ],
    updates: [
      { type: 'indication', message: 'FDA approved for prurigo nodularis in adults', date: '2022-09-19' },
      { type: 'indication', message: 'FDA approved for eosinophilic esophagitis in patients 12 years and older', date: '2022-05-20' },
    ],
  },
  logs: [],
};
